version: "3.8"

services:
  backend:
    build: ./backend
    container_name: financeapp-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_USER=admin
      - DB_HOST=192.168.0.26
      - DB_NAME=app_finance
      - DB_PASS=Al253900
      - DB_PORT=32768
      - JWT_SECRET=01a9fd0eaeafa451d8f0d24d91e30c95af14b02413d62c2101a67264343627ee
      - SERVER_HOST=localhost
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: financeapp-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
