version: "3.8"

networks:
  financeapp-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24  # 🔹 Define um range fixo de IPs

services:
  db:
    image: postgres:14
    container_name: financeapp-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Al253900
      POSTGRES_DB: app_finance
    ports:
      - "5432:5432"
    networks:
      financeapp-network:
        ipv4_address: 192.168.1.100  # 🔹 IP fixo do PostgreSQL

  backend:
    build: ./backend
    container_name: financeapp-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_USER=admin
      - DB_HOST=financeapp-db  # 🔹 Use o nome do container do PostgreSQL
      - DB_NAME=app_finance
      - DB_PASS=Al253900
      - DB_PORT=5432
      - JWT_SECRET=01a9fd0eaeafa451d8f0d24d91e30c95af14b02413d62c2101a67264343627ee
      - SERVER_HOST=financeapp-backend
    depends_on:
      - db
    networks:
      financeapp-network:
        ipv4_address: 192.168.1.101  # 🔹 IP fixo do Backend

  frontend:
    build:
      context: ./frontend
    container_name: financeapp-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      financeapp-network:
        ipv4_address: 192.168.1.102  # 🔹 IP fixo do Frontend
